export enum Entities {
    User = 'USER',
    Repository = 'REPOSITORY',
};

export enum Constants {
    REQUEST_USERS = 'REQUEST_USERS',
    SET_USERS = 'SET_USERS',
    SET_USERS_RESOLVED = 'SET_USERS_RESOLVED',
    REQUEST_REPOSITORIES = 'REQUEST_REPOSITORIES',
    SET_REPOSITORIES = 'SET_REPOSITORIES',
    SET_REPOSITORIES_RESOLVED = 'SET_REPOSITORIES_RESOLVED',
    SET_ENTITY = 'SET_ENTITY'
}
